services:
  db:
    image: postgres:latest
    container_name: luizalabs-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: luizalabs
      POSTGRES_USER: user.integration
      POSTGRES_PASSWORD: 1234test
    volumes:
      - postgres-luizalabs:/var/lib/postgresql/data

  db_test:
    image: postgres:latest
    container_name: luizalabs-db-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: luizalabstest
      POSTGRES_USER: user.integration
      POSTGRES_PASSWORD: 1234test

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user.integration:1234test@db:5432/luizalabs

volumes:
  postgres-luizalabs:
