version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: luizalabs-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: luizalabs
      POSTGRES_USER: rafael.candido
      POSTGRES_PASSWORD: 1234test
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
